{
    "markdownlint.config": {
        "MD028": false,
        "MD025": {too)
            "front_matter_title": ""0.02++++++
        }02.02+RF7.36m+m++*~~~~                                                                                                 
        id ya really think, I’d just forgive and forget…no
After catching you with her…your blood should run cold...so cold
you…you two timing, cheap lying, wannabe  
you’re a fool…if you thought that I’d just let this go
 
I SEE RED, RED, OH RED
GUN TO YOUR HEAD, HEAD, TO YOUR HEAD
NOW ALL I SEE IS RED, RED RED
 
Did ya really just say, she didn’t mean anything…oh
I’ll remember those words, when I come for your soul…your soul
You know that you…you dug your own grave…now lie in it 
you’re so cruel…but revenge is a dish best served cold
 
I SEE RED, RED, OH RED
GUN TO YOUR HEAD, HEAD, TO YOUR HEAD…OH
EXECUTIONER STYLE, AND THERE WON’T BE NO TRIAL
DON’TCHA KNOW THAT YOU’RE BETTER OFF DEAD
ALL I SEE RED, RED, OH RED
NOW ALL I SEE IS…
 
Run...hide…you’re so…done
Better sleep with one eye open tonight
 
I SEE RED, RED, OH RED
GUN TO YOUR HEAD, HEAD, TO YOUR HEAD…OH
EXECUTIONER STYLE, AND THERE WON’T BE NO TRIAL
DON’TCHA KNOW THAT YOU’RE BETTER OFF DEAD
ALL I SEE RED, RED, OH RED
NOW ALL I SEE IS…

         
        
    }
}
